name: AngelaWomackMakeup&Hair
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8209476009942591
  lightness: 0.610129255335778
  saturation: 0.7377848513424397
  rhythmicContrast: 0.29996314854361117
purpose: []
