name: Angela Womack Makeup & Hair
favicon: null
layout_spectrum: 0.00698
typography_spectrum: 0.20063
title: Angela Womack Makeup and Hair Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aefddc'
    - '#9e9187'
    - '#ccc5bf'
    - '#d4bd62'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
