name: Angela Womack Makeup & Hair
favicon: null
layout_spectrum: 0.00698
typography_spectrum: 0.20063
title: Angela Womack Makeup and Hair Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9088a5'
    - '#141505'
    - '#594d6d'
    - '#442a26'
    - '#dfbcbd'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
