name: AngelaWomackMakeup&Hair
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aefddc'
    - '#9e9187'
    - '#ccc5bf'
    - '#d4bd62'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
